#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test case below to test the API endpoints.
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::DefaultApi');

my $api = WWW::SwaggerClient::DefaultApi->new();
isa_ok($api, 'WWW::SwaggerClient::DefaultApi');

#
# calls_get test
#
{
    my $rpt_type = undef; # replace NULL with a proper value
    my $rpt_id = undef; # replace NULL with a proper value
    my $start = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $sort_by = undef; # replace NULL with a proper value
    my $sort_type = undef; # replace NULL with a proper value
    my $from_date = undef; # replace NULL with a proper value
    my $to_date = undef; # replace NULL with a proper value
    my $duration = undef; # replace NULL with a proper value
    my $phone = undef; # replace NULL with a proper value
    my $phone1 = undef; # replace NULL with a proper value
    my $co = undef; # replace NULL with a proper value
    my $ext = undef; # replace NULL with a proper value
    my $pbx_id = undef; # replace NULL with a proper value
    my $call_source = undef; # replace NULL with a proper value
    my $call_type = undef; # replace NULL with a proper value
    my $direction = undef; # replace NULL with a proper value
    my $caller_name = undef; # replace NULL with a proper value
    my $did = undef; # replace NULL with a proper value
    my $dnis = undef; # replace NULL with a proper value
    my $acc = undef; # replace NULL with a proper value
    my $ring = undef; # replace NULL with a proper value
    my $cost = undef; # replace NULL with a proper value
    my $group = undef; # replace NULL with a proper value
    my $result = $api->calls_get(rpt_type => $rpt_type, rpt_id => $rpt_id, start => $start, limit => $limit, sort_by => $sort_by, sort_type => $sort_type, from_date => $from_date, to_date => $to_date, duration => $duration, phone => $phone, phone1 => $phone1, co => $co, ext => $ext, pbx_id => $pbx_id, call_source => $call_source, call_type => $call_type, direction => $direction, caller_name => $caller_name, did => $did, dnis => $dnis, acc => $acc, ring => $ring, cost => $cost, group => $group);
}

#
# features_charts_get test
#
{
    my $result = $api->features_charts_get();
}

#
# features_reports_get test
#
{
    my $result = $api->features_reports_get();
}

#
# features_widget_get test
#
{
    my $result = $api->features_widget_get();
}


1;
